name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +0777 ./src/gradle-5.2.1/bin/gradle
    - name: Getting Gradlew
      run: ./src/gradle-5.2.1/bin/gradle wrapper --gradle-version 5.2.1 --distribution-type all
    - name: Build with Gradle
      run: ./src/gradle-5.2.1/bin/gradle build
