name: Java CI

on: push

jobs:
 build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-node@div
    - name: Set up JDK 1.8
      uses: actions/setup-java@div
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build


